<section class="container">
   
    <section class="options">
        
        <section class="search">
            <form action="/search" method="post">
                <input type="text" name="search" id="search">
                <button type="submit">Pesquisar</button>
            </form>        
        </section>
        
        <button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#addModal">Adicionar</button>
        <button type="button" class="btn btn-warning" data-bs-toggle="modal" data-bs-target="#editModal">Editar</button>
        <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#deleteModal">Deletar</button>
    
    </section>

    <section class="list">
        <table>
            <tr>
                <th>Nome</th>
                <th>Endereço</th>
                <th>Telefone</th>
            </tr>
            <tr>
                <td>Davi Sales</td>
                <td>email@email.com</td>
                <td>(98) 95678-1256</td>
            </tr>
            <tr>
                <td>Davi Sales</td>
                <td>email@email.com</td>
                <td>(98) 95678-1256</td>
            </tr>
        </table>
    </section>

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Modal title</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                ...
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
            </div>
        </div>
    </div>
</section>