<section class="container">
   
    <section class="options">
        
        <section class="search">
            <form action="/search" method="post">
                <input type="text" name="search" id="search">
                <button type="submit">Pesquisar</button>
            </form>        
        </section>
        
        <a href="#">Adicionar</a>
        <a href="#">Editar</a>
        <a href="#">Deletar</a>
    
    </section>

    <section class="list">
        <table>
            <th>
                <td>Nome</td>
                <td>Endereço</td>
                <td>Telefone</td>
            </th>
            <tr>
                <td>Davi Sales</td>
                <td>email@email.com</td>
                <td>(98) 95678-1256</td>
            </tr>
            <tr>
                <td>Davi Sales</td>
                <td>email@email.com</td>
                <td>(98) 95678-1256</td>
            </tr>
        </table>
    </section>

</section>
